language: objective-c
osx_image: xcode8

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Routing"
    - IOS_SDK=iphonesimulator10.0
    - OSX_SDK=macosx10.12
    - TVOS_SDK=appletvsimulator10.0
    - WATCHOS_SDK=watchsimulator3.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="iOS"     SDK="$IOS_SDK"     ACTION="test"
    - DESTINATION="arch=x86_64"                    SCHEME="OSX"     SDK="$OSX_SDK"     ACTION="test"
    - DESTINATION="OS=10.0,name=Apple TV 1080p"     SCHEME="tvOS"    SDK="$TVOS_SDK"    ACTION="build"
    - DESTINATION="OS=3.0,name=Apple Watch - 42mm" SCHEME="watchOS" SDK="$WATCHOS_SDK" ACTION="build"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME $SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=NO
    "$ACTION"
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

