language: objective-c
osx_image: xcode10.2

install:
  - gem install xcpretty

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Routing"
    - IOS_SDK=iphonesimulator12.2
    - OSX_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.2
    - WATCHOS_SDK=watchsimulator5.2
  matrix:
    - DESTINATION="OS=12.2,name=iPhone X"     SCHEME="iOS"     SDK="$IOS_SDK"     ACTION="test"
    - DESTINATION="arch=x86_64"                    SCHEME="OSX"     SDK="$OSX_SDK"     ACTION="test"
    - DESTINATION="OS=12.2,name=Apple TV"     SCHEME="tvOS"    SDK="$TVOS_SDK"    ACTION="build"
    - DESTINATION="OS=5.2,name=Apple Watch Series 4 - 44mm" SCHEME="watchOS" SDK="$WATCHOS_SDK" ACTION="build"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK_NAME.xcodeproj"
    -scheme "$FRAMEWORK_NAME $SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=NO
    "$ACTION"
    | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

